spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seaportdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: christianp99
    password: cri3137548063
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  port : 8090